### ISSUE TITLE
gen_usms_xml2txt with both species in sole crop

### ISSUE THREAD

**Issue by VEZY** [SticsRPacks/SticsRFiles#3]
## Current Behavior

`gen_usms_xml2txt()` returns an error for usms where both plants are parameterized, but nbplantes is set to 1, e.g.:

```xml
    <usm nom="SC_Pea_2005-2006_N0">
        <datedebut>269</datedebut>
        <datefin>575</datefin>
        <finit>SC_2005-2006_N0_ini.xml</finit>
        <nomsol>AuzAS6-N0</nomsol>
        <fstation>auzevilj_sta.xml</fstation>
        <fclim1>auzevilj.2005</fclim1>
        <fclim2>auzevilj.2006</fclim2>
        <culturean>0</culturean>
        <nbplantes>1</nbplantes>
        <codesimul>0</codesimul>
        <plante dominance="1">
            <fplt>Pea_Eric_plt.xml</fplt>
            <ftec>SC_Pea_2005-2006_N0_tec.xml</ftec>
            <flai>defaut.lai</flai>
        </plante>
        <plante dominance="2">
            <fplt>example_plant.xml</fplt>
            <ftec>example_tec.xml</ftec>
            <flai></flai>
        </plante>
    </usm>
```

This should be a valid usm because only plant 1 should be read. 

## Failure Information

Here is an example error returned by the function:
![image](https://user-images.githubusercontent.com/12777793/105478594-a9047b80-5ca3-11eb-8da4-a2357f6c144a.png)

I found out the function tries to locate the files of plant 2 in this case, but it shouldn't. 

## Proposed solution

Add a check on nbplantes first, and read only information for plant 1 if nbplantes=1.

**Comment by plecharpent** [comment]
Have been fixed, including also tec files selection.
