### ISSUE TITLE
The tutorial fail when getting the Stics Distrib

### ISSUE THREAD

**Issue by Chabrier** [SticsRPacks/SticsRFiles#4]
The curl call is not correct...4 at leat one reason: the path of the archive has changed.

Maybe a fix could be to apply the same policy than the one form SticsOnR.

I mean : instead of installing Stics from the tutorial, considering that the availability of Stics is a prerequisite.

I did test this new behaviour, and it does work, i use the javastics_path to set the work_dir.

Patches to explain what i did are available there 
* https://github.com/Chabrier/SticsRFiles/commit/bc9e02dad2a7db4a92d1cf1bcea98d3aa4f37b66#diff-b20c521ecdd7677083683c7ee7f1336d7fe1f9d0b026f4e89e6cb0ec57031ea1
* https://github.com/Chabrier/SticsRFiles/commit/1429dce925a11b3ce8fc883c0cc37867f790df64#diff-b20c521ecdd7677083683c7ee7f1336d7fe1f9d0b026f4e89e6cb0ec57031ea1

**Comment by Chabrier** [comment]
Previous Patches are deprecated.
They were not reliable.
I had to understand how exercice chunk, setup and params could work together or not.
This is of course only a propostion tested when running in rstudio.
https://github.com/Chabrier/SticsRFiles/commits/master/inst/tutorials/use-xml-files/use-xml-files.Rmd

**Comment by sbuis** [comment]
Hi Patrick,

Thanks for reporting the bug and for the proposition of improvement.
Patrice has fixed the link.
We are in the rush to finalize the SticsRpacks tutorial and will come back after that to the SticsRFiles one to consider your suggestion.

All the best,
Samuel

De : Patrick Chabrier ***@***.***>
Envoyé : jeudi 17 juin 2021 18:13
À : SticsRPacks/SticsRFiles ***@***.***>
Cc : Subscribed ***@***.***>
Objet : Re: [SticsRPacks/SticsRFiles] The tutorial fail when getting the Stics Distrib (#4)


Previous Patches are deprecated.
They were not reliable.
I had to understand how exercice chunk, setup and params could work together or not.
This is of course only a propostion tested when running in rstudio.
https://github.com/Chabrier/SticsRFiles/commits/master/inst/tutorials/use-xml-files/use-xml-files.Rmd

**Comment by Chabrier** [comment]
Hi,

very small fix provided...(merge request) Do whatever you want with it :)

with this fix the tutorials does start well from my rstudio.

By the way when launching the tutorial from the dedicated rstudio tab, the tutorial does start, 
BUT exercices that uses variables defined outside of the chunk are not working.
I believe this is the normal behaviour "exercice chunk" are "isolated".
the setup chunk, ore special setup chunk can be used, but this does not provide a complete solution,
since "params" of the header stays are not reachable.
The only way to make all the variables predefined accessible inside exercices is to parametrize and to compute this variables
directly in the setup chunks. They are computed "at exercice run time".

@+,

P

**Comment by plecharpent** [comment]
Hi Patrick,
Thanks for your fix (It has been merged) and for your feedback about parameterization of the tutorial. 
Patrice.
