### ISSUE TITLE
get_soils_list on usms.xml not a good behavior since refactoring

### ISSUE THREAD

**Issue by Chabrier** [SticsRPacks/SticsRFiles#41]
# get_soils_list on usms.xml broken

## Expected Behavior

```
path <- get_examples_path(file_type = "xml")

# Read from a usms file (soils used in a USM):
soil_list <- get_soils_list(file = file.path(path, "usms.xml"))

# Read from a soil file (all soil types available in a soil file)
soil_list <- get_soils_list(file = file.path(path, "sols.xml"))

soil_list <- get_soils_list(file = file.path(path, "usms.xml"),
                            soil = c("solcanne", "sole"))
```
should return a list with soil names

## Current Behavior

return an empty list

## Probably

Not enough introspection.
* On the soil side, we should parse node param values.
* On the usm side, we should parse node values

**Comment by plecharpent** [comment]
Thanks for reporting this issue.
Yes, the previous version of an underlying function was working with get_param_xml which was doing the job.
A missing case has been added in the branch attached to this issue.
And missing test on this function has been added.
