### ISSUE TITLE
reimplement get_param_info: for not using XML files anymore

### ISSUE THREAD

**Issue by plecharpent** [SticsRPacks/SticsRFiles#44]
Its execution time is quite long, and does not give parameters definition as it is available in get_var_info.

This function can be changed to use the inputs.csv file to get information about parameters.
In that case the formalism information will not be available (but for the moment it's buggy, see #43 )

**Implementation**
A generic function could be defined using as base the existing get_var_info function and 2 specific functions get_param_info and get_var_info that will call the new base function

**Comment by sbuis** [comment]
Definitely a good idea :-)

Maybe some additional information could also be integrated into the inputs.csv file (e.g. "are plant parameters specific or varietal ones")
