### ISSUE TITLE
gen_usms_xml2txt either more efficient or parallelized

### ISSUE THREAD

**Issue by Chabrier** [SticsRPacks/SticsRFiles#9]
It could be very convenient to optimize the conversion from xml workspaces to txt workspaces.
Especially when dealing with big experimental plan involving exogenous databases.

Best Regards

**Comment by VEZY** [comment]
Yep, we agree on this. This is in the pipes already, but we need to ditch the dependency to JavaStics for doing that. Patrice already wrote most of the code in here: https://github.com/SticsRPacks/SticsRFiles/blob/master/R/convert_xml2txt.R

We just need to check that everything works well, and apply the transformations to all files correctly, while managing the files versions according to the model version.

**Comment by Chabrier** [comment]
Thanks for the feedback. 
I've seen this also. And i did try to use this approach.
In my case some things are missing, in the SticsV10 distrib i'm using, i do not see where the xslt files are stored.
And also it's not clear to me by reading the code if the usms.xml converting process is covered also.
Any way, i'm ready to test :) as soon as the feature is available, since i have noticed that the converting process takes more time than the simulating one.
Thanks for the work.

**Comment by plecharpent** [comment]
Hi,
All the stuff and functionnalities have been added to avoid using the JavaStics command line in the [plecharpent/feat/XML-transfo](https://github.com/SticsRPacks/SticsRFiles/tree/plecharpent/feat/XML-transfo) branch.
The usms files generation duration is now divided by 4. 
The gen_usms_xml2txt is then much more effiicient but not parallelized yet.
You can test it now from the given branch.
We will test parallelization from inside the function soon.
All the best.
